version: "3"
services:
  app:
    container_name: prodmean
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: nishta06/prodmean
    ports:
      - "8080:8080"
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
